version: 1.0.{build}

build:
  verbosity: minimal

environment:
  matrix:
  - CMAKE_GENERATOR: Visual Studio 15 2017
    BUILD_TYPE: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

before_build:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -DMM2_GAME_DIRECTORY="%cd%/output" -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE="%BUILD_TYPE%"
  - cmd: cmake --build . --config "%BUILD_TYPE%" --target "install"

artifacts:
  - path: build/output
    name: OpenMM2
    type: zip
